name: Issue Remove Active Label On Close

on:
  issues: { types: closed }

jobs:
  remove-active-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.5.0
        with:
          script: |
            github.issues.removeLabel({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              name: 'active'
            })
